package com.wechatgroupmsg.mapper;

import com.wechatgroupmsg.entity.ChatroomEntity;
import com.wechatgroupmsg.entity.ChatroomEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatroomEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    long countByExample(ChatroomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int deleteByExample(ChatroomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int insert(ChatroomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int insertSelective(ChatroomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    List<ChatroomEntity> selectByExampleWithBLOBs(ChatroomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    List<ChatroomEntity> selectByExample(ChatroomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    ChatroomEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatroomEntity record, @Param("example") ChatroomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ChatroomEntity record, @Param("example") ChatroomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatroomEntity record, @Param("example") ChatroomEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatroomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ChatroomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatroom
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatroomEntity record);
}