package com.wechatgroupmsg.mapper;

import com.wechatgroupmsg.entity.GroupMsgEntity;
import com.wechatgroupmsg.entity.GroupMsgEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMsgEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    long countByExample(GroupMsgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int deleteByExample(GroupMsgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int insert(GroupMsgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int insertSelective(GroupMsgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    List<GroupMsgEntity> selectByExampleWithBLOBs(GroupMsgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    List<GroupMsgEntity> selectByExample(GroupMsgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    GroupMsgEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupMsgEntity record, @Param("example") GroupMsgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GroupMsgEntity record, @Param("example") GroupMsgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupMsgEntity record, @Param("example") GroupMsgEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupMsgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GroupMsgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupMsgEntity record);
}