package com.wechatgroupmsg.mapper;

import com.wechatgroupmsg.entity.GroupMsg;
import com.wechatgroupmsg.entity.GroupMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    long countByExample(GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int deleteByExample(GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int insert(GroupMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int insertSelective(GroupMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    List<GroupMsg> selectByExampleWithBLOBs(GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    List<GroupMsg> selectByExample(GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    GroupMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupMsg record, @Param("example") GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GroupMsg record, @Param("example") GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupMsg record, @Param("example") GroupMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GroupMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupMsg record);
}