package com.wechatgroupmsg.entity;

public class ChatroomEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatroom.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatroom.chatroomname
     *
     * @mbg.generated
     */
    private String chatroomname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatroom.roomowner
     *
     * @mbg.generated
     */
    private String roomowner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatroom.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatroom.memberlist
     *
     * @mbg.generated
     */
    private String memberlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatroom.id
     *
     * @return the value of chatroom.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatroom.id
     *
     * @param id the value for chatroom.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatroom.chatroomname
     *
     * @return the value of chatroom.chatroomname
     *
     * @mbg.generated
     */
    public String getChatroomname() {
        return chatroomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatroom.chatroomname
     *
     * @param chatroomname the value for chatroom.chatroomname
     *
     * @mbg.generated
     */
    public void setChatroomname(String chatroomname) {
        this.chatroomname = chatroomname == null ? null : chatroomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatroom.roomowner
     *
     * @return the value of chatroom.roomowner
     *
     * @mbg.generated
     */
    public String getRoomowner() {
        return roomowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatroom.roomowner
     *
     * @param roomowner the value for chatroom.roomowner
     *
     * @mbg.generated
     */
    public void setRoomowner(String roomowner) {
        this.roomowner = roomowner == null ? null : roomowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatroom.update_time
     *
     * @return the value of chatroom.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatroom.update_time
     *
     * @param updateTime the value for chatroom.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatroom.memberlist
     *
     * @return the value of chatroom.memberlist
     *
     * @mbg.generated
     */
    public String getMemberlist() {
        return memberlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatroom.memberlist
     *
     * @param memberlist the value for chatroom.memberlist
     *
     * @mbg.generated
     */
    public void setMemberlist(String memberlist) {
        this.memberlist = memberlist == null ? null : memberlist.trim();
    }
}